//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.Resources.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string ActualSettings {
            get {
                return ResourceManager.GetString("ActualSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia domyślne.
        /// </summary>
        public static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz przywrócić ustawienia domyślne? Tej operacji nie da się cofnąć!.
        /// </summary>
        public static string DefaultSettingsConfirmation {
            get {
                return ResourceManager.GetString("DefaultSettingsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulowano przywracanie ustawień domyślnych..
        /// </summary>
        public static string DefaultSettingsNOTOK {
            get {
                return ResourceManager.GetString("DefaultSettingsNOTOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przywrócono ustawienia domyślne..
        /// </summary>
        public static string DefaultSettingsOK {
            get {
                return ResourceManager.GetString("DefaultSettingsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrany folder zawierający pliki DLL to: .
        /// </summary>
        public static string DialogChooseDLLFolder {
            get {
                return ResourceManager.GetString("DialogChooseDLLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrany plik: .
        /// </summary>
        public static string DialogChooseGraphFileResult {
            get {
                return ResourceManager.GetString("DialogChooseGraphFileResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki tekstowe|*.txt.
        /// </summary>
        public static string DialogChooseGraphFilter {
            get {
                return ResourceManager.GetString("DialogChooseGraphFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrany folder: .
        /// </summary>
        public static string DialogChooseGraphFolderResult {
            get {
                return ResourceManager.GetString("DialogChooseGraphFolderResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano żadnego pliku..
        /// </summary>
        public static string DialogChooseGraphNoFile {
            get {
                return ResourceManager.GetString("DialogChooseGraphNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano żadnego folderu..
        /// </summary>
        public static string DialogChooseGraphNoFolder {
            get {
                return ResourceManager.GetString("DialogChooseGraphNoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik tekstowy zawierający reprezentację grafu.
        /// </summary>
        public static string DialogChooseGraphTitle {
            get {
                return ResourceManager.GetString("DialogChooseGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono pliku DLL w podanej lokalizacji: .
        /// </summary>
        public static string DllFileMissing {
            get {
                return ResourceManager.GetString("DllFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Bit .
        /// </summary>
        public static string GraphCPUB {
            get {
                return ResourceManager.GetString("GraphCPUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Table .
        /// </summary>
        public static string GraphCPUT {
            get {
                return ResourceManager.GetString("GraphCPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU .
        /// </summary>
        public static string GraphGPU {
            get {
                return ResourceManager.GetString("GraphGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się wykonać obliczeń.
        ///Przewidywana ilość pamięci RAM potrzebna do wykonania obliczeń: .
        /// </summary>
        public static string GraphRunErrorNoSpaceAvailable {
            get {
                return ResourceManager.GetString("GraphRunErrorNoSpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MB.
        ///Zadanie zakończone niepowodzeniem..
        /// </summary>
        public static string GraphRunErrorNoSpaceEndLine {
            get {
                return ResourceManager.GetString("GraphRunErrorNoSpaceEndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MB, 
        ///pamięć dostępna (wirtualna): .
        /// </summary>
        public static string GraphRunErrorNoSpaceRequired {
            get {
                return ResourceManager.GetString("GraphRunErrorNoSpaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieoczekiwany błąd, plik .
        /// </summary>
        public static string GraphRunErrorPartOne {
            get {
                return ResourceManager.GetString("GraphRunErrorPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Upewnij się, że Twoja maszyna posiada kartę NVIDIA, która wspiera technologię CUDA..
        /// </summary>
        public static string GraphRunErrorPartThree {
            get {
                return ResourceManager.GetString("GraphRunErrorPartThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  nie został przetworzony.
        ///Kod błędu: .
        /// </summary>
        public static string GraphRunErrorPartTwo {
            get {
                return ResourceManager.GetString("GraphRunErrorPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy format pliku z grafem. Zakończono wykonywanie obliczeń: .
        /// </summary>
        public static string GraphRunErrorReadingInput {
            get {
                return ResourceManager.GetString("GraphRunErrorReadingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niestety nie można było estymować czasu potrzebnego na wykonanie obliczeń - za mało danych..
        /// </summary>
        public static string GraphRunPredictTimeNoData {
            get {
                return ResourceManager.GetString("GraphRunPredictTimeNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przewidywany czas wykonywania obliczeń: .
        /// </summary>
        public static string GraphRunPredictTimeStart {
            get {
                return ResourceManager.GetString("GraphRunPredictTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba chromatyczna grafu wynosi: .
        /// </summary>
        public static string GraphRunResultPartOne {
            get {
                return ResourceManager.GetString("GraphRunResultPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        ///Czas obliczeń: .
        /// </summary>
        public static string GraphRunResultPartTwo {
            get {
                return ResourceManager.GetString("GraphRunResultPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatycznie utworzono plik logu: .
        /// </summary>
        public static string LogFileNotExist {
            get {
                return ResourceManager.GetString("LogFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mniej niż sekundę.
        /// </summary>
        public static string PredictTimeLessThanSecond {
            get {
                return ResourceManager.GetString("PredictTimeLessThanSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przetwarzanie metodą .
        /// </summary>
        public static string PredictTimeMethodInfo {
            get {
                return ResourceManager.GetString("PredictTimeMethodInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Rozpoczynam obliczenia dla pliku: .
        /// </summary>
        public static string PreprocessingFirst {
            get {
                return ResourceManager.GetString("PreprocessingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string PreprocessingForth {
            get {
                return ResourceManager.GetString("PreprocessingForth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Liczba wierzchołków grafu: .
        /// </summary>
        public static string PreprocessingSecond {
            get {
                return ResourceManager.GetString("PreprocessingSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Gęstość grafu: .
        /// </summary>
        public static string PreprocessingThird {
            get {
                return ResourceManager.GetString("PreprocessingThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano pliku, ani folderu z plikami zawierającymi reprezentację grafu..
        /// </summary>
        public static string RunNoInputData {
            get {
                return ResourceManager.GetString("RunNoInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano żadnej metody algorytmu rozwiązującego problem..
        /// </summary>
        public static string RunNoMethod {
            get {
                return ResourceManager.GetString("RunNoMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulowano obliczenie.
        /// </summary>
        public static string RunTaskCancelled {
            get {
                return ResourceManager.GetString("RunTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozróżniane są małe i wielkie litery.
        /// </summary>
        public static string SetPatternDesc {
            get {
                return ResourceManager.GetString("SetPatternDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualny wzorzec wyszukiwania plików w folderze: .
        /// </summary>
        public static string SetPatternResult {
            get {
                return ResourceManager.GetString("SetPatternResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz wzorzec do wyszukania odpowiednich plików w wybranym folderze.
        /// </summary>
        public static string SetPatternTitle {
            get {
                return ResourceManager.GetString("SetPatternTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany wzorzec jest pusty! W przypadku uruchomienia algorytmu z wybranym folderem zostaną przetworzone wszystkie pliki znajdujące się w folderze!.
        /// </summary>
        public static string SetPatternWarning {
            get {
                return ResourceManager.GetString("SetPatternWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano.
        /// </summary>
        public static string SettingsBlankDefault {
            get {
                return ResourceManager.GetString("SettingsBlankDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Ścieżka do folderu z plikami DLL: .
        /// </summary>
        public static string SettingsDllPath {
            get {
                return ResourceManager.GetString("SettingsDllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka do danych z reprezentacją grafu: .
        /// </summary>
        public static string SettingsGraphPath {
            get {
                return ResourceManager.GetString("SettingsGraphPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy wybrana ścieżka wskazuje na plik (P), czy folder (F): .
        /// </summary>
        public static string SettingsIsFile {
            get {
                return ResourceManager.GetString("SettingsIsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string SettingsIsFileADirectory {
            get {
                return ResourceManager.GetString("SettingsIsFileADirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string SettingsIsFileAFile {
            get {
                return ResourceManager.GetString("SettingsIsFileAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka do pliku z logiem: .
        /// </summary>
        public static string SettingsLogFilePath {
            get {
                return ResourceManager.GetString("SettingsLogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wzorzec, wg którego będą wybierane pliki z folderu (jeżeli dotyczy): .
        /// </summary>
        public static string SettingsPattern {
            get {
                return ResourceManager.GetString("SettingsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka do pliku ze statystykami: .
        /// </summary>
        public static string SettingsStatsFilePath {
            get {
                return ResourceManager.GetString("SettingsStatsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W bieżącej sesji nie wykonano żadnych obliczeń. Brak statystyk do wyświetlenia..
        /// </summary>
        public static string StatsZeroRun {
            get {
                return ResourceManager.GetString("StatsZeroRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zainstalowanego programu Adobe Reader. Zainstaluj najnowszą wersję w celu otworzenia pliku z pomocą..
        /// </summary>
        public static string ViewHelpNoAdobeReader {
            get {
                return ResourceManager.GetString("ViewHelpNoAdobeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups... nie znaleziono pliku pomocy :(.
        /// </summary>
        public static string ViewHelpNoFile {
            get {
                return ResourceManager.GetString("ViewHelpNoFile", resourceCulture);
            }
        }
    }
}
